env:
  commonjs: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - single
  require-await: 0